### ISSUE TITLE
Add to MELPA?

### ISSUE THREAD

**Issue by flexibeast** [xuchunyang/region-state.el#2]
Could you please consider [adding this package to MELPA](https://github.com/milkypostman/melpa#contributing-new-recipes)? Thanks in anticipation!

**Comment by xuchunyang** [comment]
It has been on MELPA for some time: http://melpa.org/#/region-state. Thanks for reminding me, anyway.

**Comment by flexibeast** [comment]
That's odd. It wasn't showing up in package-list-packages when i checked earlier .... Now it is. %-} Sorry for the noise!
