### ISSUE TITLE
C-g should stop showing the info

### ISSUE THREAD

**Issue by mrBliss** [xuchunyang/region-state.el#4]
Steps to reproduce:

* <kbd>C-SPC</kbd>
* <kbd>C-g</kbd>
* The region info is still shown in the minibuffer after every command.

I fixed this in my config by adding an advice around `region-state--display-in-echo-area` that calls `region-state--deactivate` when `mark-active` is nil.

**Comment by xuchunyang** [comment]
I can't reproduce by following your steps. region-state.el only shows region stat when there is a reasonable region, when using <kbd>C-g</kbd> to deactivate a region, the function `region-state--deactive` will eventually be called through `deactivate-mark-hook`.

**Comment by mrBliss** [comment]
You are right, I can't reproduce it using a vanilla Emacs. It must be something in my config then. I'll just use the advice for now.
